New feat: Add mod key optine for auto translate
windingwind/zotero-pdf-translate pull request #266
Opened 2022-10-18 13:09 UTC by Trzeth

Mod key is a sub-optine of auto translate. Selected text will be translate unless you press the key.
I like to select text for no reason, and the popup keeps annoy me.
Therefore I add this optine to make popup show up at the right time.

2022-10-18 16:50 UTC, windingwind commented on src/prefs.ts
> +  updateModKeySettings() {
No need to manually update the checkbox value to prefs. Just bind in the XUL.

2022-10-18 16:54 UTC, windingwind requested changes

2022-10-18 16:54 UTC, windingwind commented on src/events.ts
> +        let enableModKey = Zotero.Prefs.get("ZoteroPDFTranslate.enableModKey");
Alt is for concat translation and shift is the range selection. Might be misleading if these two keys are used for other functions.

2022-10-19 00:15 UTC, Trzeth commented on src/prefs.ts
> +  updateModKeySettings() {
Sry, Don't quite understand. A example will be thankful.

2022-10-19 00:15 UTC, Trzeth commented on src/events.ts
> +        let enableModKey = Zotero.Prefs.get("ZoteroPDFTranslate.enableModKey");
But Ctrl still have promblem. When you press Ctrl in advance you can't select text for no reason.
So should I remove alt and shift or leave it?

2022-10-19 00:31 UTC, volatile-static commented on src/events.ts
> +        let enableModKey = Zotero.Prefs.get("ZoteroPDFTranslate.enableModKey");
Why don't use <kbd>T</kbd>?

2022-10-19 00:31 UTC, volatile-static commented on src/prefs.ts
> +  updateModKeySettings() {
Can prefs auto bind two checkbox? @windingwind

2022-10-19 02:13 UTC, windingwind commented on addon/chrome/content/preferences.xul
> +                      <checkbox id="zotero-prefpane-__addonRef__-settings-enable-mod-key" preference="pref-__addonRef__-enable-mod-key" oncommand="Zotero.ZoteroPDFTranslate.prefs.updateModKeySettings
The `preference` attribute binds to the `<preference/> element in line 12, which will make the prefs with corresponding `id` pref-__addonRef__-enable-mod-key. The checkbox is already binded to a pref.

2022-10-19 02:16 UTC, windingwind commented on src/events.ts
> +        let enableModKey = Zotero.Prefs.get("ZoteroPDFTranslate.enableModKey");
As @volatile-static states, we already have a T or Ctrl+T shortcut, which works in both library view and PDF viewer.

2022-10-19 03:12 UTC, Trzeth commented on src/events.ts
> +        let enableModKey = Zotero.Prefs.get("ZoteroPDFTranslate.enableModKey");
You're right, I can totally use T and Ctrl T to replace this feat with auto translate is off and popup is on.
But mod key can block popup (result or translate btn) show up, maybe this means a lot to me.
I know it's all for my convenience, feel free to leave it.

2022-10-19 03:19 UTC, Trzeth commented on addon/chrome/content/preferences.xul
> +                      <checkbox id="zotero-prefpane-__addonRef__-settings-enable-mod-key" preference="pref-__addonRef__-enable-mod-key" oncommand="Zotero.ZoteroPDFTranslate.prefs.updateModKeySettings
Sorry, still don't understand. I use the `updateModKeySettings()` func to modify the disable value of radio group and checkbox with logic. Do you mean this can be done in XUL with binding? If so, i just can't find a example by google and it's hard to debug with XUL Explorer. A example would be thankful.
Or I just don't get the idea?

2022-10-19 04:40 UTC, volatile-static commented on addon/chrome/content/preferences.xul
> +                      <checkbox id="zotero-prefpane-__addonRef__-settings-enable-mod-key" preference="pref-__addonRef__-enable-mod-key" oncommand="Zotero.ZoteroPDFTranslate.prefs.updateModKeySettings
我怀疑你俩说的不是一个事。
@windingwind 说的是你勾选checkbox时zotero会自动保存prefs。
但 @Trzeth 的代码是在绑定两个checkbox的勾选状态。

2022-10-19 04:43 UTC, volatile-static commented on src/events.ts
> +        let enableModKey = Zotero.Prefs.get("ZoteroPDFTranslate.enableModKey");
But even disable the translate add-on, zotero still pop a panel when you select text.
I don't know how you hide that popup?

2022-10-21 15:11 UTC, windingwind commented on addon/chrome/content/preferences.xul
> +                      <checkbox id="zotero-prefpane-__addonRef__-settings-enable-mod-key" preference="pref-__addonRef__-enable-mod-key" oncommand="Zotero.ZoteroPDFTranslate.prefs.updateModKeySettings
> 我怀疑你俩说的不是一个事。

You are right. My bad.

2022-10-21 15:13 UTC, windingwind commented on src/events.ts
> +        let enableModKey = Zotero.Prefs.get("ZoteroPDFTranslate.enableModKey");
> I know it's all for my convenience, feel free to leave it.

Maybe you could post and issue about this PR and let other users decide whether we should merge it.

2022-10-21 15:14 UTC, windingwind commented on src/prefs.ts
> +  updateModKeySettings() {
> Can prefs auto bind two checkbox? @windingwind

No

2022-11-11 09:16 UTC, windingwind commented
I'll see if it would be possible to hide the popup.

2023-04-05 05:24 UTC, windingwind commented
Closed for #426 has partly resolved this.

2023-04-05 05:24 UTC, closed without merging