add: Haici Dict(Dict.cn)
windingwind/zotero-pdf-translate pull request #298
Opened 2022-11-20 03:31 UTC by MuiseDestiny

![image](https://user-images.githubusercontent.com/51939531/202881331-bcf22cba-1895-418d-b568-40460a299192.png)
dict.cn海词词典很好用，于是加入了，有四个朗读，英美都对应男女

但是这里有个报错，我不知道怎么修复，注释后才可以运行
![image](https://user-images.githubusercontent.com/51939531/202881364-572629ee-51ba-4ca4-96e3-99d4849ce309.png)

2022-11-20 09:17 UTC, windingwind requested changes

2022-11-20 09:17 UTC, windingwind commented on addon/chrome/locale/zh-CN/overlay.dtd
> +<!ENTITY zotero.__addonRef__llins.pref.advanced.showSidebarLanguage.label "侧边栏: 显示语言选择菜单">
这里是否误修改

2022-11-20 09:17 UTC, windingwind commented on addon/chrome/content/preferences.xul
> -                        <row>
请复原此处

2022-11-20 09:33 UTC, windingwind commented
感谢贡献代码，已将有问题的部分标出

2022-11-20 11:04 UTC, MuiseDestiny commented on addon/chrome/content/preferences.xul
> -                        <row>
已修复问题并复原，测试可以显示设置菜单了

2022-11-21 02:16 UTC, windingwind commented
> 这个接口的sl和tl可能有自己的表述方式

可以在xftrans.ts里加一个国标语言代码-讯飞语言代码的映射即可

2022-11-21 03:11 UTC, MuiseDestiny commented
> > 这个接口的sl和tl可能有自己的表述方式
> 
> 可以在xftrans.ts里加一个国标语言代码-讯飞语言代码的映射即可

好的，只映射了中文，其他的split("-")[0]就正常转换过去了。

2022-11-21 06:02 UTC, windingwind reviewed
Thanks!

2022-11-21 06:03 UTC, windingwind approved these changes

2022-11-21 06:03 UTC, merged