feat: support Azure OpenAI
windingwind/zotero-pdf-translate pull request #584
Opened 2023-09-13 16:06 UTC by Maasea

支持 Azure 提供的 chatGPT 接口

PS:
由于后续对 gpt 模块的完善，使其支持了第三方接口。由于不同第三方提供的功能不一致，可能无法正确获取 OpenAI 模型，所以更改成手动填写，也不再利用获取模型的方式检测接口是否可用。

2023-09-13 17:08 UTC, windingwind requested changes
Thank you for the PR! Looks good, with a few comments to be addressed.

2023-09-13 17:08 UTC, windingwind commented on src/modules/services/gpt.ts
> +  apiURL: Required<string>,
Don't need `Required` on basic types

2023-09-13 17:08 UTC, windingwind commented on src/modules/services/index.ts
> +      (e) => (this.azuregpt = new TranslateTaskRunner(e.azureGPT)),
Merge these two imports from the same module in one `import` callback

2023-09-14 01:27 UTC, Maasea commented
Done.

2023-09-14 02:14 UTC, windingwind approved these changes

2023-09-14 02:14 UTC, merged