Add Gemini API
windingwind/zotero-pdf-translate pull request #669
Opened 2023-12-24 09:52 UTC by sasaju

增加Gemini API，如有需要后续可补充帮助Gist
使用时需保证访问Gemini的IP为受支持的地区，如美国、新加坡。（所有支持地区可在此查看：https://ai.google.dev/available_regions#available_regions）
目前API使用暂时免费，可在此申请：https://ai.google.dev/tutorials/setup

2023-12-24 10:51 UTC, windingwind requested changes

2023-12-24 10:51 UTC, windingwind commented on src/modules/popup.ts
> +  // @ts-ignore
Please remove this

2023-12-24 10:51 UTC, windingwind commented on src/modules/reader.ts
> +      // @ts-ignore
Please remove this

2023-12-24 10:56 UTC, sasaju commented on src/modules/reader.ts
> +      // @ts-ignore
they removed

2023-12-24 10:56 UTC, sasaju commented on src/modules/popup.ts
> +  // @ts-ignore
removed

2023-12-25 08:15 UTC, windingwind approved these changes

2023-12-25 08:15 UTC, merged